// Generates src/catalogue/pricing-data.ts from inventory.json — a trimmed,
// bundle-able pricing projection (price-relevant fields only) for the browser-clean
// @broberg/ai-sdk/pricing subpath (F027). Runs in `build`, like gen-version.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const inv = JSON.parse(readFileSync(join(root, "inventory.json"), "utf8"));
const models = Array.isArray(inv.models) ? inv.models : [];

const rows = models.map((m) => ({
  provider: String(m.provider ?? ""),
  model: String(m.model ?? ""),
  name: String(m.name ?? m.model ?? ""),
  input: Number(m.pricing?.input ?? 0),
  output: Number(m.pricing?.output ?? 0),
  unit: String(m.pricing?.unit ?? "per_1m_tokens"),
  region: String(m.region ?? "other"),
}));

const out =
  `// GENERATED by scripts/gen-pricing.mjs from inventory.json — DO NOT EDIT.\n` +
  `// Trimmed pricing projection bundled into the @broberg/ai-sdk/pricing subpath (F027).\n` +
  `// Regenerated whenever inventory.json refreshes (monthly F014/F017.5 cron).\n` +
  `export interface ModelPriceRaw {\n` +
  `  provider: string; model: string; name: string;\n` +
  `  input: number; output: number; unit: string; region: string;\n` +
  `}\n` +
  `export const PRICING_GENERATED_AT = ${JSON.stringify(String(inv.generatedAt ?? ""))};\n` +
  `export const PRICING_DATA: ModelPriceRaw[] = ${JSON.stringify(rows)};\n`;

writeFileSync(join(root, "src/catalogue/pricing-data.ts"), out);
console.log(`[gen-pricing] wrote src/catalogue/pricing-data.ts → ${rows.length} models (as of ${inv.generatedAt ?? "?"})`);
