// Build-time version stamp. tsconfig has rootDir:"src", so `import "../package.json"`
// is illegal from src/. Instead we write src/version.ts (gitignored) from package.json
// before tsup runs, so the SDK can self-report its version (e.g. in upmetrics tags.sdk).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(here, "..", "package.json"), "utf8"));
const out = join(here, "..", "src", "version.ts");

writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit, do not commit.\n` +
    `export const VERSION = ${JSON.stringify(pkg.version)} as const;\n` +
    `export const SDK_TAG = ${JSON.stringify(`${pkg.name}@${pkg.version}`)} as const;\n`,
);

console.log(`[gen-version] wrote src/version.ts → ${pkg.name}@${pkg.version}`);
